### ISSUE TITLE
In parachute, FAIL shold take an erroring form

### ISSUE THREAD

**Issue by Yehouda** [phoe/protest#11]
in src/parachute/test.lisp, it has a form `(fail :failure)`, which doesn't give the expected result, because **fail** in parachute expects the form it takes to invoke **error**. In the bottom the file there is an output of running the tests showing this test fails. 

It should take a form that invokes error, for example `(fail (* 3 :a))`.

**Comment by phoe** [comment]
Acknowledged, I'll fix this.
