### ISSUE TITLE
Feature request: add protocol extension definition

### ISSUE THREAD

**Issue by sirherrbatka** [phoe/protest#3]
It is fairly common to construct extended protocol based upon existing ones. It would be therefore useful to be able to specify :includes option for protocol.

**Comment by phoe** [comment]
Protocols can now depend on each other: if you create protocol A and protocol B that depends on A and protocol C that depends on B and A, then protocol C depends on B and A being defined. Additionally, A, B and C may not contain duplicate entries, for example, a function named `FOO` cannot be defined in protocols A and C at the same time.

Does this functionality solve this issue?

**Comment by phoe** [comment]
Closing due to no response from issue author, and hope that protocol dependencies are what the author wanted.
