### ISSUE TITLE
Need to use :mix when using both closer-mop and common-lisp

### ISSUE THREAD

**Issue by Yehouda** [phoe/protest#6]
in src/base/package.lisp it uses both **common-lisp** and **closer-mop**, which create various clashes. It tries to get over it by using **:shadowing-import-from,** but because **closer-mop** either import from the implementation or create new symbols in some cases, it doesn't work form all implementations. The current version errors on LispWorks because both **closer-mop** and **common-lisp** export **standard-class**.

**uiop:define-package** has a keyword **:mix** that can be used instead of **:use** to cope with these situations. Just change the **:use** to **:mix** fixes the problem, and it can run the 1am tests successfully.

**Comment by phoe** [comment]
Thanks for the ticket! Please let me know if https://github.com/phoe/protest/commit/d705a02e9fb098839ec044c1cdcdadd4a4e55eeb fixes your issue.

**Comment by Yehouda** [comment]
I don't actually pull the code from git, I download the quicklisp system. I changed by hand the code from quicklisp like your suggested change, and then it loads properly and successfuly run the 1am test.

**Comment by phoe** [comment]
OK. The new PROTEST version should be picked up by the next Quicklisp update, which should happen within a few days.

Also, thanks for using PROTEST!
