### ISSUE TITLE
The switch to :around is not complete, remove-protocol-object still looks for :before

### ISSUE THREAD

**Issue by Yehouda** [phoe/protest#7]
in src/base/base.lisp, **remove-protocol-object ** needs to pass **'(:around)** to**find-method** with **#'initialize-instance**, to match what **define-protocol-object** does. 

It gives an error when quikcloadloading "protest/test-case" and calling **(protest/test:run-all-tests)**. With this change **(protest/test:run-all-tests)** it runs successfully.

**Comment by phoe** [comment]
Thanks for the catch! Fixed.
